spring:
  profiles: dev
xinerji:
  jms:
    username: JMS Username
    password: somepass-DEV
    url: http://jms11.org
  database:
    url: jdbc:postgresql://***
    username: postgres
    password: ***
    driver: org.postgresql.Driver


---
spring:
  profiles: test
xinerji:
  jms:
    username: JMS Username
    password: somepass-TEST
    url: http://jms11.org
  database:
    url: jdbc:postgresql://***
    username: postgres
    password: ***
    driver: org.postgresql.Driver
    
---
spring:
  profiles: prod
xinerji:
  jms:
    username: JMS Username
    password: somepass-PROD
    url: http://jms11.org
  database:
    url: jdbc:postgresql://***
    username: postgres
    password: ***
    driver: org.postgresql.Driver
